apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruity2
spec:
  selector:
    matchLabels:
      app: nginx2
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 7809
